from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
import sys
from typing import Any


DEFAULT_SCOPE = "user"
DEFAULT_LAYER = "semantic"
DEFAULT_TYPE = "fact"


def memory_candidate_writer(**skill_inputs: Any) -> dict[str, Any]:
    repo_root = _repo_root()
    backend_path = repo_root / "backend"
    if str(backend_path) not in sys.path:
        sys.path.insert(0, str(backend_path))

    from app.memory import store

    candidates = _coerce_candidates(skill_inputs.get("candidates"))
    if isinstance(candidates, dict):
        return _result([], [candidates])

    source_defaults = _source_defaults(skill_inputs)
    persisted: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    for index, item in enumerate(candidates):
        normalized, error = _normalize_candidate(item, index=index, source_defaults=source_defaults)
        if error is not None:
            skipped.append(error)
            continue
        try:
            persisted.append(
                store.create_memory(
                    normalized,
                    changed_by="memory_candidate_writer",
                    change_reason="Memory candidate generated by graph review.",
                )
            )
        except Exception as exc:
            skipped.append(
                {
                    "index": index,
                    "error_type": "write_failed",
                    "error": str(exc),
                    "summary": normalized.get("summary", ""),
                }
            )
    return _result(persisted, skipped)


def _coerce_candidates(value: Any) -> list[Any] | dict[str, Any]:
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            return {"index": None, "error_type": "invalid_candidates", "error": f"candidates must be JSON: {exc}"}
        return _coerce_candidates(parsed)
    if value is None:
        return []
    if not isinstance(value, list):
        return {"index": None, "error_type": "invalid_candidates", "error": "candidates must be an array."}
    return value


def _normalize_candidate(
    value: Any,
    *,
    index: int,
    source_defaults: dict[str, str],
) -> tuple[dict[str, Any], dict[str, Any] | None]:
    if not isinstance(value, dict):
        return {}, {"index": index, "error_type": "invalid_candidate", "error": "candidate must be an object."}
    summary = _as_text(value.get("summary") or value.get("title")).strip()
    content = _as_text(value.get("content")).strip()
    if not summary:
        return {}, {"index": index, "error_type": "missing_summary", "error": "candidate summary is required."}
    if not content:
        return {}, {"index": index, "error_type": "missing_content", "error": "candidate content is required."}

    evidence = _normalize_list(value.get("evidence"))
    if not evidence:
        return {}, {"index": index, "error_type": "missing_evidence", "error": "candidate evidence is required."}

    source = _normalize_dict(value.get("source"))
    for key, default_value in source_defaults.items():
        if default_value:
            source[key] = default_value

    normalized = {
        "scope": _normalize_label(value.get("scope"), DEFAULT_SCOPE),
        "layer": _normalize_label(value.get("layer"), DEFAULT_LAYER),
        "type": _normalize_label(value.get("type") or value.get("memory_type"), DEFAULT_TYPE),
        "summary": summary,
        "content": content,
        "confidence": _normalize_float(value.get("confidence"), 0.7),
        "importance": _normalize_float(value.get("importance"), 0.5),
        "evidence": evidence,
        "artifact_refs": _normalize_list(value.get("artifact_refs") or value.get("artifactRefs")),
        "source": source,
        "status": "candidate",
        "supersedes": _normalize_list(value.get("supersedes")),
    }
    return normalized, None


def _result(candidate_memories: list[dict[str, Any]], skipped_candidates: list[dict[str, Any]]) -> dict[str, Any]:
    success = not skipped_candidates
    result_text = (
        f"Created {len(candidate_memories)} memory candidates."
        if success
        else f"Created {len(candidate_memories)} memory candidates; skipped {len(skipped_candidates)}."
    )
    return {
        "success": success,
        "candidate_memories": candidate_memories,
        "skipped_candidates": skipped_candidates,
        "result": result_text,
        "activity_events": [
            {
                "kind": "memory_candidate_write",
                "summary": result_text,
                "status": "succeeded" if success else "failed",
                "detail": {
                    "candidate_count": len(candidate_memories),
                    "skipped_count": len(skipped_candidates),
                    "candidate_ids": [candidate.get("id") for candidate in candidate_memories],
                    "skipped_candidates": deepcopy(skipped_candidates),
                },
            }
        ],
    }


def _source_defaults(skill_inputs: dict[str, Any]) -> dict[str, str]:
    return {
        "run_id": _as_text(skill_inputs.get("run_id")).strip(),
        "node_id": _as_text(skill_inputs.get("node_id")).strip(),
        "template_id": _as_text(skill_inputs.get("template_id")).strip(),
    }


def _normalize_dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _normalize_list(value: Any) -> list[Any]:
    return list(value) if isinstance(value, list) else []


def _normalize_label(value: Any, default: str) -> str:
    text = _as_text(value).strip().lower().replace(" ", "_")
    if not text:
        return default
    normalized = "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in text)
    return normalized[:80] or default


def _normalize_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


if __name__ == "__main__":
    payload = json.loads(sys.stdin.read() or "{}")
    print(json.dumps(memory_candidate_writer(**payload), ensure_ascii=False))
